.github/pull_request_template.md
We don't have a PR template file and probably should. This adds one.
=> Chore/create pull_request_template.md file

components/case-studies-card/case-studies-card.module.scss, components/features/features.tsx, components/testimonials/testimonials.module.scss
Signed-off-by: Tynan DeBold <thdebold@gmail.com>
Resolves #30 
Just some small tweaks based on the issue.
Take a look at the deployed link.
=> Small text and style updates

components/feature-details-card/feature-details-card.module.scss, components/features/features-content.tsx, components/features/features.tsx, components/media/media.test.tsx, components/ready-to-start/ready-to-start.tsx, components/why-kedro/why-kedro.module.scss, components/why-kedro/why-kedro.tsx, styles/_mixins.scss, styles/_variables.scss
Signed-off-by: Tynan DeBold <thdebold@gmail.com>
Resolves #39.
One small style and HTML addition.
Take a look at the deployed URL, make the screen small, and check the gradient. Note: the background color doesn't match yet. It will once @rashidakanchwala is done with her in-progress ticket.
=> add gradient to the nav on mobile only

components/companies-using-kedro/companies-using-kedro.tsx
Signed-off-by: Yetunde Dada [yetunde.dada@quantumblack.com](mailto:yetunde.dada@quantumblack.com)
This PR was created to update the title of `McKinsey & Company`; it needs a capital `K`.
=> Update company title

components/footer/footer.tsx, components/header/header.tsx, package-lock.json
Signed-off-by: Tynan DeBold <thdebold@gmail.com>
Resolves #54 
I've updated the links.
Make sure the Discord logo links go to Linen.
=> Update discord links to linen.dev

components/faq/faq.tsx
=> Update faqs section title

modules/index/footer/footer.test.tsx, modules/index/footer/footer.tsx
=> Add blog link to footer

modules/blog/post-body/post-body.tsx
Fixes an issue where sometimes the header values in Contentful mess up the page rendering.
Make the function accept objects as well as strings.
=> Make headerTextToIdString fn more robust

modules/blog/post-body/post-body.module.scss, modules/blog/post-body/post-body.tsx
Resolves #117.
Using the awesome `IntersectionObserver` and some cool stuff with React `refs` and JS `Map`.
Here's all the newness: 
Play around with the deployed URL to get a feel for yourself!
=> Highlight sticky nav in posts and add link underlines

pages/_app.tsx
Resolves #123.
https://nextjs.org/docs/messages/next-script-for-ga
@stichbury you should see some data trickling through. Can you please check?
I've added this to the entire site, not just the blog. And I won't enable this on deploy previews, as I don't want to muddy the waters.
=> Add Google Analytics

modules/index/features/features-content.tsx, modules/index/why-kedro/why-kedro.tsx
Resolves #114
Check the deploy preview.
=> Update YouTube videos to be sourced from Kedro's account

modules/blog/posts-list/posts-list.module.scss, modules/blog/posts-list/posts-list.tsx
Fixes #122.
Check the deploy preview link on a mobile device: https://deploy-preview-126--kedro-website.netlify.app/
=> Remove hover on mobile for post links

modules/index/why-kedro/why-kedro.module.scss, modules/index/why-kedro/why-kedro.test.tsx, modules/index/why-kedro/why-kedro.tsx, styles/_variables.scss
Resolves #134 
https://github.com/kedro-org/kedro-website/assets/32060364/9d3db50d-0f2b-419f-8630-d5c6ba73f755
NOTES:
- The gradient block currently only applies to the top of the text box. The reason for it is that in order to make the mouse scrollable anywhere on the "Why Kedro" section, I didn't set the fixed height/max height as in the design. Therefore, it's very hard to set the gradient block for the bottom of the section as there is no fixed height anymore. 
Let me know what you think on this @Mackay031 @stephkaiser?
=> Update why kedro module

modules/index/faq/faq-content.ts, modules/index/faq/faq.tsx
See https://github.com/kedro-org/kedro-devrel/issues/40
=> Mention awesome-kedro for community content

modules/blog/post-body/post-body.module.scss, modules/blog/post-body/post-body.tsx
Resolves [#131](https://github.com/kedro-org/kedro-website/issues/131)
Updated the colors to match Steph's guidance.
Check the post here: https://deploy-preview-146--kedro-website.netlify.app/blog/a-polars-exploration-into-kedro
=> Update code block colors

lib/api.js, modules/blog/post-body/post-body.tsx, pages/blog.tsx
Resolves #145 
I've added new content type called LinkedImage. That's fetched from GraphQL and then rendered on the page.
Question for @stichbury: do you want to be able to specific if the link opens in a new tab or not?
Take a look at the test article here to see it in action: https://deploy-preview-147--kedro-website.netlify.app/blog/test-article-dont-publish
=> Add a linked image content type

pages/_app.tsx
Closes #148.
Removed Google Analytics.
=> Remove Google Analytics

styles/_mixins.scss
Resolves #79
I've removed the styles we weren't using.
=> Remove unused header styles

lib/api.js, modules/blog/post-category-links/index.tsx, modules/blog/post-category-links/post-category-links.test.tsx, modules/blog/post-category-links/post-category-links.tsx, modules/blog/post-snippet/post-snippet.tsx, modules/blog/posts-list/posts-list.tsx, pages/blog/author/author.module.scss, pages/blog/category/[category].tsx, pages/blog/category/category.module.scss, styles/_extends.scss
Resolves #120 
I've added the category pages. You can reach them by clicking on the category/tag above each post snippet as seen here:
https://github.com/kedro-org/kedro-website/assets/16869061/33f8b195-43f3-49ed-adf4-57f6013ccd18
I haven't done any nice design work or added anything we didn't already have, given that our design team is at capacity. I thought we could add this in without really changing anything and then come back at a later date with some updated UI.
Take a look at the demo URL and see what you think.
=> Add category pages

pages/blog.tsx, pages/blog/[slug].tsx
Resolves #159 
Added the necessary `link` tag to the blog homepage and article pages.
Check the HTML source of the blog homepage and article pages.
=> Add RSS autodiscovery to blog

modules/index/footer/footer.test.tsx, modules/index/footer/footer.tsx, modules/index/hero/hero.tsx, modules/index/ready-to-start/ready-to-start.module.scss, modules/index/ready-to-start/ready-to-start.tsx, modules/shared/header/header.test.tsx, modules/shared/header/header.tsx
Resolves #173
I believe I've covered everything stated in #173.
Check the deployed link and see if I missed anything.
@stephkaiser might want to take a quick look at the code formatting in the `Ready to start?` section.
=> Update Hero CTA buttons and Ready To Start section

modules/blog/post-body/post-body.tsx, pages/blog/[slug].tsx, pages/blog/author/[author].tsx, pages/blog/category/[category].tsx, utils/blog/index.ts
Saw some console warnings for the Nextjs `Link` component. Fixed that. Also updated some small styles.
Ensure all works on the deployed URL.
=> Update small styles and add correct Link prop

modules/index/ready-to-start/ready-to-start.tsx
The YouTube link is live and now it's added.
View the deployed link and ensure the link opens to the right location.
=> Add YouTube playlist link to Ready to start? section

pages/post.module.scss
Small PR to address a tiny styling issue.
=> Fix Copy link spacing on post page

modules/index/features/features-content.tsx
Addressed https://github.com/kedro-org/kedro/issues/4883
To remove the ET section since kedro viz doesnt have that feature anymore.
=> Feat/ remove ET section

modules/index/features/features-content.tsx, modules/index/ready-to-start/ready-to-start.tsx
To ensure that all Kedro documentation links direct to the correct URLs.
=> update doc links
